IMAGE ?= ghcr.io/supersaiyane/auto-agent-k8s:1.0.0

# Pinned tool versions. `make tools` downloads them into bin/tools.
GOLANGCI_LINT_VERSION ?= v1.64.8
GOVULNCHECK_VERSION   ?= v1.1.4
TOOLS_BIN             := $(CURDIR)/bin/tools
# Ratchet base for lint: only code changed since BASE is held to golangci-lint.
BASE                  ?= origin/master

.PHONY: build test lint vet docker push helm-install clean tools vuln check-writing helm-lint verify verify-full e2e e2e-raw manifests check-manifests coverage-check

VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)

build:
	CGO_ENABLED=0 go build -ldflags="-X main.version=$(VERSION)" -o bin/auto-agent ./cmd/auto-agent

test:
	go test -race -count=1 -coverprofile=coverage.out ./...

coverage-check:
	sh scripts/coverage-check.sh

test-cover:
	go test -race -coverprofile=coverage.out ./...
	go tool cover -func=coverage.out
	@echo ""
	@echo "HTML report: go tool cover -html=coverage.out"

vet:
	go vet ./...

tools:
	GOBIN=$(TOOLS_BIN) go install github.com/golangci/golangci-lint/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)
	GOBIN=$(TOOLS_BIN) go install golang.org/x/vuln/cmd/govulncheck@$(GOVULNCHECK_VERSION)

lint: vet
	@test -x $(TOOLS_BIN)/golangci-lint || { echo "golangci-lint missing: run 'make tools'"; exit 1; }
	$(TOOLS_BIN)/golangci-lint run --new-from-rev=$(BASE) ./...

vuln:
	@test -x $(TOOLS_BIN)/govulncheck || { echo "govulncheck missing: run 'make tools'"; exit 1; }
	$(TOOLS_BIN)/govulncheck ./...

check-writing:
	sh scripts/check-writing.sh

helm-lint:
	helm lint charts/auto-agent

# verify is the definition-of-done gate (CLAUDE.md). vuln joined it on
# 2026-10-07 once govulncheck was clean (ISS-016).
verify: build vet test coverage-check lint vuln check-writing helm-lint check-manifests

# Kept for muscle memory; verify already includes vuln.
verify-full: verify

e2e:
	sh scripts/e2e-kind.sh

# The generated raw manifests on their own kind cluster (ISS-050).
e2e-raw:
	sh scripts/e2e-raw.sh

# Every applied file in deployment/ is generated from the chart, so the raw
# manifests cannot drift from it (ISS-009, ISS-050). The Secret is not among
# them: deployment/ensure-secret.sh creates it once and never overwrites it
# (ISS-048). CI regenerates and fails on any difference.
RAW_VALUES = --set namespace=auto-agent --set "agent.namespaceAllowlist={default,test1,test2}" \
	--set image.repository=auto-agent --set image.tag=latest --set image.pullPolicy=IfNotPresent
RAW_HEADER = echo "\# GENERATED by make manifests from charts/auto-agent; do not edit."
manifests:
	{ $(RAW_HEADER); cat charts/auto-agent/crds/*.yaml; } > deployment/01-crds.yaml
	{ $(RAW_HEADER); helm template auto-agent charts/auto-agent $(RAW_VALUES) \
	    --show-only templates/serviceaccount.yaml --show-only templates/clusterrole.yaml \
	    --show-only templates/clusterrolebinding.yaml --show-only templates/roles.yaml; } > deployment/02-rbac.yaml
	{ $(RAW_HEADER); helm template auto-agent charts/auto-agent $(RAW_VALUES) \
	    --show-only templates/configmap.yaml; } > deployment/03-config.yaml
	{ $(RAW_HEADER); helm template auto-agent charts/auto-agent $(RAW_VALUES) \
	    --show-only templates/daemonset.yaml --show-only templates/controller.yaml \
	    --show-only templates/service.yaml --show-only templates/networkpolicy.yaml; } > deployment/04-agent.yaml

# Fails when deployment/ differs from what the chart renders (ISS-050).
check-manifests: manifests
	git diff --exit-code -- deployment/

tidy:
	go mod tidy

docker:
	docker build --build-arg VERSION=$(VERSION) -t $(IMAGE) .

push:
	docker push $(IMAGE)

helm-install:
	helm upgrade --install auto-agent charts/auto-agent -n kube-system --create-namespace

helm-template:
	helm template auto-agent charts/auto-agent

clean:
	rm -rf bin/ coverage.out
