package kube

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"go.yaml.in/yaml/v3"
)

// PatchWorkloadMemory raises one workload's memory limit in a Helm values
// file: the value at <workload>.resources.limits.memory, at any depth. It
// patches only when exactly one key named after the workload holds that
// path, and refuses otherwise rather than guess, so a shared environment
// file never has another service's memory changed (ISS-083). Comments are
// kept; the file is re-encoded with two-space indentation.
func PatchWorkloadMemory(content, workload string, bumpPercent int) (string, string, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(content), &doc); err != nil {
		return "", "", fmt.Errorf("parse values file: %w", err)
	}
	var hits []*yaml.Node
	walkMappings(&doc, func(key string, val *yaml.Node) {
		if key == workload {
			if m := mappingPath(val, "resources", "limits", "memory"); m != nil && m.Kind == yaml.ScalarNode {
				hits = append(hits, m)
			}
		}
	})
	switch len(hits) {
	case 0:
		return "", "", fmt.Errorf("no %s.resources.limits.memory in the values file", workload)
	case 1:
	default:
		return "", "", fmt.Errorf("%d keys named %s hold resources.limits.memory; not guessing which", len(hits), workload)
	}
	old := hits[0].Value
	mi, ok := memoryMi(old)
	if !ok {
		return "", "", fmt.Errorf("memory limit %q is not a whole number of Mi or Gi", old)
	}
	// Work in Mi: bumping "1Gi" as the integer 1 rounds to nothing (and
	// roundUpNice's steps are Mi).
	newVal := fmt.Sprintf("%dMi", roundUpNice(mi+mi*bumpPercent/100))
	hits[0].Value = newVal
	var b bytes.Buffer
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return "", "", fmt.Errorf("encode values file: %w", err)
	}
	if err := enc.Close(); err != nil {
		return "", "", fmt.Errorf("encode values file: %w", err)
	}
	return b.String(), fmt.Sprintf("%s.resources.limits.memory %s -> %s (+%d%%)", workload, old, newVal, bumpPercent), nil
}

// walkMappings calls fn for every key and value of every mapping in the tree.
func walkMappings(n *yaml.Node, fn func(key string, val *yaml.Node)) {
	if n.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(n.Content); i += 2 {
			fn(n.Content[i].Value, n.Content[i+1])
		}
	}
	for _, c := range n.Content {
		walkMappings(c, fn)
	}
}

// mappingPath follows keys through nested mappings; nil when one is missing.
func mappingPath(n *yaml.Node, keys ...string) *yaml.Node {
	for _, k := range keys {
		if n.Kind != yaml.MappingNode {
			return nil
		}
		var next *yaml.Node
		for i := 0; i+1 < len(n.Content); i += 2 {
			if n.Content[i].Value == k {
				next = n.Content[i+1]
			}
		}
		if next == nil {
			return nil
		}
		n = next
	}
	return n
}

// memoryMi reads "512Mi" or "2Gi" as Mi.
func memoryMi(s string) (int, bool) {
	for unit, scale := range map[string]int{"Mi": 1, "Gi": 1024} {
		if num, ok := strings.CutSuffix(s, unit); ok {
			v, err := strconv.Atoi(num)
			return v * scale, err == nil && v > 0
		}
	}
	return 0, false
}

// roundUpNice rounds a memory value to a nice number (power of 2 or multiple of 64).
func roundUpNice(v int) int {
	// For values under 1024, round up to nearest 64
	if v <= 1024 {
		return ((v + 63) / 64) * 64
	}
	// For larger values, round up to nearest 256
	return ((v + 255) / 256) * 256
}

// GenerateMemoryBumpContent creates a kustomize-style patch file that bumps
// one container's memory limit, for when no values file can be patched.
func GenerateMemoryBumpContent(ns, workload, container, currentLimit string, bumpPercent int) (string, string) {
	// Generate a kustomize-style strategic merge patch
	currentMi := parseMemoryMi(currentLimit)
	newMi := currentMi + (currentMi * bumpPercent / 100)
	newMi = roundUpNice(newMi)

	patch := fmt.Sprintf(`# Auto-generated by auto-agent
# Bumps memory limit for %s/%s container %s by %d%%
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %s
  namespace: %s
spec:
  template:
    spec:
      containers:
        - name: %s
          resources:
            limits:
              memory: "%dMi"
`, ns, workload, container, bumpPercent,
		deploymentName(workload), ns, container, newMi)

	change := fmt.Sprintf("%s -> %dMi (+%d%%)", currentLimit, newMi, bumpPercent)
	return patch, change
}

func parseMemoryMi(s string) int {
	s = strings.TrimSpace(s)
	if strings.HasSuffix(s, "Gi") {
		var v int
		fmt.Sscanf(s, "%dGi", &v)
		return v * 1024
	}
	if strings.HasSuffix(s, "Mi") {
		var v int
		fmt.Sscanf(s, "%dMi", &v)
		return v
	}
	// Try plain number (bytes)
	var v int
	fmt.Sscanf(s, "%d", &v)
	return v / (1024 * 1024)
}

func deploymentName(workload string) string {
	// workload is "replicaset/name-hash" or "deployment/name"
	parts := strings.SplitN(workload, "/", 2)
	if len(parts) == 2 {
		name := parts[1]
		// Strip ReplicaSet hash suffix (last -xxxxx)
		if idx := strings.LastIndex(name, "-"); idx > 0 {
			// Check if suffix looks like a hash
			suffix := name[idx+1:]
			if len(suffix) >= 5 && len(suffix) <= 10 {
				return name[:idx]
			}
		}
		return name
	}
	return workload
}
