package kube

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// PatchMemoryInValues takes a Helm values YAML string and increases the memory
// limit for a container by the given percentage. Returns the patched content.
//
// This handles the common values.yaml pattern:
//
//	resources:
//	  limits:
//	    memory: "512Mi"
//
// It finds the memory line and bumps it.
func PatchMemoryInValues(content string, containerPath string, bumpPercent int) (string, string) {
	// Find memory limit pattern
	memPattern := regexp.MustCompile(`(?m)(^\s*memory:\s*"?)(\d+)(Mi|Gi)("?\s*)$`)

	var oldVal, newVal string
	patched := memPattern.ReplaceAllStringFunc(content, func(match string) string {
		if oldVal != "" {
			return match // only patch first match
		}
		sub := memPattern.FindStringSubmatch(match)
		if len(sub) < 5 {
			return match
		}
		prefix, numStr, unit, suffix := sub[1], sub[2], sub[3], sub[4]
		num, err := strconv.Atoi(numStr)
		if err != nil {
			return match
		}
		oldVal = fmt.Sprintf("%d%s", num, unit)
		bumped := num + (num * bumpPercent / 100)
		// Round up to nice number
		bumped = roundUpNice(bumped)
		newVal = fmt.Sprintf("%d%s", bumped, unit)
		return fmt.Sprintf("%s%d%s%s", prefix, bumped, unit, suffix)
	})

	if oldVal == "" {
		return content, ""
	}
	return patched, fmt.Sprintf("%s -> %s (+%d%%)", oldVal, newVal, bumpPercent)
}

// roundUpNice rounds a memory value to a nice number (power of 2 or multiple of 64).
func roundUpNice(v int) int {
	// For values under 1024, round up to nearest 64
	if v <= 1024 {
		return ((v + 63) / 64) * 64
	}
	// For larger values, round up to nearest 256
	return ((v + 255) / 256) * 256
}

// GenerateMemoryBumpContent creates the full file content for a GitOps PR
// that bumps memory for a workload. If valuesContent is provided, it patches
// that. Otherwise it generates a kustomize patch.
func GenerateMemoryBumpContent(valuesContent, ns, workload, container, currentLimit string, bumpPercent int) (string, string) {
	if valuesContent != "" {
		return PatchMemoryInValues(valuesContent, workload, bumpPercent)
	}

	// Generate a kustomize-style strategic merge patch
	currentMi := parseMemoryMi(currentLimit)
	newMi := currentMi + (currentMi * bumpPercent / 100)
	newMi = roundUpNice(newMi)

	patch := fmt.Sprintf(`# Auto-generated by auto-agent
# Bumps memory limit for %s/%s container %s by %d%%
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %s
  namespace: %s
spec:
  template:
    spec:
      containers:
        - name: %s
          resources:
            limits:
              memory: "%dMi"
`, ns, workload, container, bumpPercent,
		deploymentName(workload), ns, container, newMi)

	change := fmt.Sprintf("%s -> %dMi (+%d%%)", currentLimit, newMi, bumpPercent)
	return patch, change
}

func parseMemoryMi(s string) int {
	s = strings.TrimSpace(s)
	if strings.HasSuffix(s, "Gi") {
		var v int
		fmt.Sscanf(s, "%dGi", &v)
		return v * 1024
	}
	if strings.HasSuffix(s, "Mi") {
		var v int
		fmt.Sscanf(s, "%dMi", &v)
		return v
	}
	// Try plain number (bytes)
	var v int
	fmt.Sscanf(s, "%d", &v)
	return v / (1024 * 1024)
}

func deploymentName(workload string) string {
	// workload is "replicaset/name-hash" or "deployment/name"
	parts := strings.SplitN(workload, "/", 2)
	if len(parts) == 2 {
		name := parts[1]
		// Strip ReplicaSet hash suffix (last -xxxxx)
		if idx := strings.LastIndex(name, "-"); idx > 0 {
			// Check if suffix looks like a hash
			suffix := name[idx+1:]
			if len(suffix) >= 5 && len(suffix) <= 10 {
				return name[:idx]
			}
		}
		return name
	}
	return workload
}
