apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-agent
subjects:
- kind: ServiceAccount
  name: auto-agent
  namespace: {{ include "auto-agent.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-agent-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-agent-node
subjects:
- kind: ServiceAccount
  name: auto-agent-node
  namespace: {{ include "auto-agent.namespace" . }}
