#!/bin/bash
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=========================================="
echo " Deploying 3 Test Apps (9 failing pods)"
echo "=========================================="

echo ""
echo "[1/4] Creating namespaces..."
kubectl apply -f "$DIR/00-namespaces.yaml"

echo ""
echo "[2/4] Deploying payment-service to 'default' namespace..."
echo "  - payment-api:      CrashLoopBackOff (DB connection refused)"
echo "  - payment-worker:   OOMKilled (memory leak)"
echo "  - payment-gateway:  ConfigError (missing Stripe secret)"
kubectl apply -f "$DIR/app1-payment-service.yaml"

echo ""
echo "[3/4] Deploying order-service to 'test1' namespace..."
echo "  - order-api:        Init container failure (Redis unreachable)"
echo "  - order-worker:     ImagePullBackOff (bad registry)"
echo "  - order-notifier:   NotReady (failing readiness probe)"
echo "  - order-cache:      Service with 0 endpoints (blackhole)"
echo "  - order-migration:  Failed Job"
kubectl apply -f "$DIR/app2-order-service.yaml"

echo ""
echo "[4/4] Deploying inventory-service to 'test2' namespace..."
echo "  - inventory-db:     Pending (impossible resource request)"
echo "  - inventory-sync:   Restart storm (exits every 1s)"
echo "  - inventory-api:    Healthy v1 (will break later for stuck rollout)"
echo "  - inventory-quota:  Tight ResourceQuota"
kubectl apply -f "$DIR/app3-inventory-service.yaml"

echo ""
echo "=========================================="
echo " Test Apps Deployed!"
echo "=========================================="
echo ""
echo "  Failures happening NOW:"
echo "    default/payment-api        -> CrashLoopBackOff       (30s)"
echo "    default/payment-worker     -> OOMKilled               (10s)"
echo "    default/payment-gateway    -> CreateContainerConfigError (immediate)"
echo "    test1/order-api            -> Init:CrashLoopBackOff   (30s)"
echo "    test1/order-worker         -> ImagePullBackOff        (15s)"
echo "    test1/order-notifier       -> NotReady                (3 min)"
echo "    test1/order-cache          -> 0 endpoints             (2 min scan)"
echo "    test1/order-migration      -> Job Failed              (2 min scan)"
echo "    test2/inventory-db         -> Pending                 (5 min)"
echo "    test2/inventory-sync       -> Restart storm           (1 min)"
echo ""
echo "  Open dashboard: http://localhost:8080"
echo "  Watch agent:    kubectl logs -n auto-agent -l app=auto-agent -f"
echo ""
echo "  To trigger STUCK ROLLOUT (after 1 min):"
echo "    kubectl set image deploy/inventory-api api=registry.invalid/broken:v2 -n test2"
echo ""
echo "  To clean up:"
echo "    ./deployment/test-apps/remove-apps.sh"
echo ""
